### PR TITLE
Add dmg2img

### PR DESCRIPTION
**Pull request by davidxbors**
This commit adds dmg2img, a tool used by iExtractor-manager.

### CODE REVIEW

**Comment by razvand** [comment]
@davidxbors, a submodule won't work. The aim of this repository (`external-tools`) is to be a safe space to store tools that may become unavailable in their initial repository / storage. If we use a submodule, we still rely on their availability in the initial repository / storage, and that beats the purpose. Add the actual contents of the initial repository / storage as a `dmg2img/` directory in this repository.

If not already part of the contents, also add a short `README.md` file, telling what the tool does and the origin of the files.

**Review by razvand — COMMENTED** [review]
Why is there both a `README` and a `README.md`? I would only leave the `README.md`. Or you want to keep the `README` for easier future updates?

**Comment by davidxbors** [comment]
> Why is there both a `README` and a `README.md`? I would only leave the `README.md`. Or you want to keep the `README` for easier future updates?

That's the way the archive comes. Also, README.md has references to README.

**Review by razvand — APPROVED** [review]
Thanks, @davidxbors, this works.

**Pull request merged**
